### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Subtixx** [Subtixx/sb-extralogics#1]
## ToDo
- [ ] Make datawire optional (Let the user pick between binary, and digital)
- [ ] Bundled "wire"
- [x] Make strings displayable on linkdisplay
- [x] Pitfall Trap has no inventory icon (it uses the one from entityscanner)
- [x] Add a way to increase the size of the pitfall trap using datawires. (See pitfall.lua)
- [x] Make GUI's
- [x] Make floats displayable on linkdisplay
## Requested
- Compat API for macrochip ([Post 2](http://steamcommunity.com/workshop/filedetails/discussion/738930584/353916184346392523/#c353916184346715494)) -> Not possible due to macrochip not providing any kind of access to add new stuff.
- Item Transportation ([Post 3](http://steamcommunity.com/workshop/filedetails/discussion/738930584/353916184346392523/#c353916184347007794)) (Move to own mod maybe? -> extratransport)

**Comment by Subtixx** [comment]
Added X and Y sizing to the Pitfall trap:
![](http://i.imgur.com/fOld4jF.png)

Added in a6dc46225891b931a93f1863b72f04154584afc3

Input node 1 is a shared between digital and analog. Sending a digital 1 means setting size X to 1. Sending an analog 1 means disabling the blocks.

**Comment by Royal-Jelly** [comment]
I completely overlooked this todo list here for a long while, and good to see you back

**Comment by Royal-Jelly** [comment]
also another recent starfoundry revival  happened here : https://github.com/ColonolNutty/CNStarFoundry

I'd recommend giving it a look as it has come quite far as well, also if you can you should get in contact with him on the starbound forums he's pretty active

**Comment by Subtixx** [comment]
Mine is more a reinterpretation than anything (This is why the mod is called extra* and not StarFoundryReborn or UpdatedStarFoundry). I used starfoundry only as a startpoint. Also it was my first mod I worked on starbound. Didn't knew shit about starbound when starting this (Which I think was ultimately my downfall). With the addition of sb-exratransport [this](https://github.com/Subtixx/sb-extralogics/wiki/Constant), [this](https://github.com/Subtixx/sb-extralogics/wiki/Pulse-Former), [this](https://github.com/Subtixx/sb-extralogics/wiki/Pulse-Extender), [this](https://github.com/Subtixx/sb-extralogics/commit/4f54d32a536614cd2001bbe098c15f1019cacb42), [this](https://github.com/Subtixx/sb-extralogics/tree/master/objects/wired/traps/pitfall) and a lot of other things that I customize for my personal likings, you can clearly see that. I didn't had much time last year due to me focusing on my own game. Sorry for that.
There is also a lot in starbound that is quite limiting. For example the upgrades in the new hopper in the new transportation mod. I had to "workaround" since you can't tell the client what is allowed and what not in a slot. ([Reference](https://github.com/Subtixx/sb-extratransportation/blob/master/objects/transport/hopper/hopper.lua#L26)) or that you only can put items facing left or right, but not up or down ([Reference](https://github.com/Subtixx/sb-extratransportation/blob/master/objects/transport/hopper/hopper.lua#L12)) or you somehow don't have access to the length of a jsonarray ([Reference](https://github.com/Subtixx/sb-extratransportation/blob/master/objects/transport/hopper/hopper.lua#L159)), or you don't have access to the first item in a container ([Reference](https://github.com/Subtixx/sb-extratransportation/blob/master/objects/transport/hopper/hopper.lua#L168)) you see where I am going with this?

I feel like hes arrogant.. I don't like him after reading through his stuff.
> I feel I'm doing a better job at cleaning up the scripts than he is,

I also started streaming my work on the mods on [Twitch](https://www.twitch.tv/subtixx)
